" ############
" Editor Setup
" ############

if has('nvim')
    " Commenting this out to maintain the same base dir for now. Configuration
    " should try to refer to s:editor_root instead of ~/.vim where possible to
    " support this changing
    " let s:editor_root=expand("~/.nvim")
    let s:editor_root=expand("~/.vim")
else
    let s:editor_root=expand("~/.vim")
endif

let mapleader=","
cmap w!! %!sudo tee > /dev/null %

" Setup runtime path
let g:loaded_python_provider = 0
let &rtp = &rtp . ',' . s:editor_root . '/bundle/Vundle.vim'
let &rtp = &rtp . ',' . s:editor_root . expand("~/.local/lib/python3.8/site-packages/powerline/bindings/vim/")
let &rtp = &rtp . ',' . s:editor_root . expand("~/.local/lib/python3.7/site-packages/powerline/bindings/vim/")
set rtp+=~/.fzf

" Disable compatibility mode
set nocompatible

set laststatus=2
set list
inoremap hh <Esc>

set listchars=tab:\▸\ ,precedes:<,extends:>
" set listchars=tab:\»\ ,

" Bindings
nnoremap <leader><leader>n :match<CR>:nohl<CR>
nnoremap <M-q> :q<CR>
nnoremap <C-s> :w<CR>
nnoremap <leader>s :w<CR>
nnoremap <leader><leader>s :Snippets<CR>
nnoremap <leader>t :vsplit term://zsh<CR>
nnoremap <leader>ba :ball<CR>
" vv or || to generate new vertical split
nnoremap <silent> vv :vnew<CR>
nnoremap <silent> <Bar><Bar> :vnew<CR>
" -- to generate new vertical split
nnoremap <silent> -- <C-w>n
nnoremap <C-t> :Files<CR>
nnoremap <CR> G
nnoremap <BS> gg
nnoremap <C-_> <Plug>TCommentMaybeInline
if filereadable('/etc/fbwhoami')
    nnoremap <silent> <leader>n :call fzf#run({'source': '~/nfs/bin/wm', 'sink': 'e'})<CR>
    " Generate URL to view section of code for sharing
    function! LinkToCode(makeFburl) range
      let fullpath = resolve(expand('%:p'))
      let linestr = line('.')
      if a:lastline - a:firstline > 0
          let linestr = a:firstline . "-" . a:lastline
      endif

      let filepos = expand("%:p") . ":" . linestr
      let urlcmd = "diffusion " . filepos
      if a:makeFburl
          let urlcmd = urlcmd . " | fburl"
      endif
      echom system(urlcmd . " 2> /dev/null")[:-2]
    endfunction

    nnoremap <leader><leader>d :call LinkToCode(0)<CR>
    vnoremap <leader><leader>d :call LinkToCode(0)<CR>
    nnoremap <leader><leader>f :call LinkToCode(1)<CR>
    vnoremap <leader><leader>f :call LinkToCode(1)<CR>
endif


inoremap <leader><leader>s <Esc>:Snippets<CR>
inoremap <C-s> <Esc>:w<CR>
inoremap <leader>s <Esc>:w<CR>

vmap Y y']

" ALE
nnoremap <leader>en :ALENextWrap<CR>
nnoremap <leader>ep :ALELastWrap<CR>

" #######
" Plugins
" #######

" Install Vundle if not present
let vundle_installed=1
let vundle_readme=s:editor_root . '/bundle/Vundle.vim/README.md'
let vundle_repo = 'https://github.com/VundleVim/Vundle.vim'

if !filereadable(vundle_readme)
    echo "Installing Vundle.."
    echo ""
    silent call mkdir(s:editor_root . '/bundle', "p")
    silent execute "!git clone " . vundle_repo . " " . s:editor_root . "/bundle/Vundle.vim"
    let vundle_installed=0
endif

augroup balancebot
    autocmd!
    " Report to Balance Bot
    autocmd VimEnter * silent exec "!(~/bin/balance.sh vim_open &) > /dev/null"
    autocmd VimLeave * silent exec "!(~/bin/balance.sh vim_close &) > /dev/null"
    autocmd BufReadPost,StdinReadPost * silent exec "!(~/bin/balance.sh file_open &) > /dev/null"
    autocmd BufWritePost * silent exec "!(~/bin/balance.sh file_save &) > /dev/null"
augroup END


" Required for bug in Vundle - re-enable after plugin shit
filetype plugin off

call vundle#rc(s:editor_root . '/bundle')
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

" Syntax plugins
Plugin 'tmhedberg/SimpylFold'
Plugin 'gabrielelana/vim-markdown'
Plugin 'trapd00r/irc.vim'
Plugin 'PotatoesMaster/i3-vim-syntax'
Plugin 'ClockworkNet/vim-junos-syntax'
Plugin 'nathanalderson/yang.vim'
Plugin 'mitsuhiko/vim-jinja'
Plugin 'sheerun/vim-polyglot'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'fatih/vim-go'

" Color schemes
Plugin 'tomasr/molokai'
Plugin 'joshdick/onedark.vim'
Plugin 'drewtempelmeyer/palenight.vim'
Plugin 'altercation/vim-colors-solarized'

Plugin 'guns/xterm-color-table.vim'

" Airline
" Plugin 'joshdick/airline-onedark.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Utility plugins
Plugin 'w0rp/ale'
Plugin 'autozimu/LanguageClient-neovim'
Plugin 'coxley/codepad'
Plugin 'keith/gist.vim'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'suan/vim-instant-markdown'
Plugin 'dhruvasagar/vim-table-mode'
Plugin 'powerline/powerline'
Plugin 'kana/vim-fakeclip'
Plugin 'jlfwong/vim-arcanist'
Plugin 'phleet/vim-mercenary'
Plugin 'hynek/vim-python-pep8-indent'
Plugin 'tpope/vim-abolish'
Plugin 'junegunn/fzf.vim'
Plugin 'christoomey/vim-tmux-navigator'

" Powerhouse plugins
Plugin 'rhysd/vim-grammarous'
Plugin 'Rykka/riv.vim'
Plugin 'Rykka/InstantRst'
Plugin 'sjl/gundo.vim'
Plugin 'tomtom/tcomment_vim'
Plugin 'scrooloose/nerdtree'
Plugin 'godlygeek/tabular'
Plugin 'Shougo/deoplete.nvim'
Plugin 'zchee/deoplete-go'
" Vim go completion
" Plugin 'nsf/gocode', {'rtp': 'vim/'}
" Plugin 'zchee/deoplete-jedi'
Plugin 'davidhalter/jedi-vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'ervandew/supertab'
" Plugin 'Yggdroot/indentLine'
Plugin 'terryma/vim-expand-region'

" Distraction free
Plugin 'junegunn/goyo.vim'
Plugin 'junegunn/limelight.vim'

" C++
Plugin 'vim-scripts/a.vim'

" Web Development
" Plugin 'mattn/emmet-vim'
Plugin 'chrisbra/Colorizer'
Plugin 'jelera/vim-javascript-syntax'

if vundle_installed == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
    :PluginInstall
    :GoInstallBinaries
endif

call vundle#end()
filetype plugin indent on

" Disable Background Color Erase (BCE) so that color schemes
" work properly when Vim is used inside tmux and GNU screen.

" if &term =~ '256color'
"     set t_ut=
" endif
"

" #########
" Filetypes
" #########

au BufRead,BufNewFile Dockerfile set ft=Dockerfile
au BufRead,BufNewFile *.pp set ts=2 sw=2 sts=2 filetype=puppet
au BufRead,BufNewFile *.thrift set ts=2 sw=2 sts=2 expandtab ft=thrift
au BufRead,BufNewFile *.go set noexpandtab
au BufRead,BufNewFile *.j2 set ts=2 sw=2 sts=2 expandtab ft=jinja
au BufRead,BufNewFile *.rb set ts=2 sw=2 sts=2 expandtab
au BufRead,BufNewFile *.yaml set ts=2 sw=2 sts=2 expandtab ft=yaml
au BufRead,BufNewFile *.yml set ts=2 sw=2 sts=2 expandtab ft=yaml

au BufRead,BufNewFile *.html set ts=2 sw=2 sts=2 filetype=html
au BufRead,BufNewFile *.css set ts=2 sw=2 sts=2 filetype=css
au BufRead,BufNewFile *.js set ts=2 sw=2 sts=2 filetype=js

au BufRead,BufNewFile *.cconf set filetype=python
au BufRead,BufNewFile *.mcconf set filetype=python
au BufRead,BufNewFile *.cinc set filetype=python
au BufRead,BufNewFile *.tw set filetype=python
au BufRead,BufNewFile TARGETS set filetype=bzl
if filereadable('/etc/fbwhoami')
    let g:python3_host_prog='/home/coxley/virtualenvs/neovim/bin/python'
    let g:python_host_prog='/home/coxley/virtualenvs/neovim2/bin/python'
    " Autofmt TARGETS files
    autocmd BufWritePre TARGETS silent! exec "!~/bin/buckfmt -i %" | :e
endif

autocmd BufWritePre *.go :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.py :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.cinc :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.cconf :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.mcconf :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.tw :call LanguageClient#textDocument_formatting()

" ##############
" Split and tabs
" ##############
"
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Merge tab functions
function MoveToPrevTab()
  "there is only one window
  if tabpagenr('$') == 1 && winnr('$') == 1
    return
  endif
  "preparing new window
  let l:tab_nr = tabpagenr('$')
  let l:cur_buf = bufnr('%')
  if tabpagenr() != 1
    close!
    if l:tab_nr == tabpagenr('$')
      tabprev
    endif
    sp
  else
    close!
    exe "0tabnew"
  endif
  "opening current buffer in new window
  exe "b".l:cur_buf
endfunc

function MoveToNextTab()
  "there is only one window
  if tabpagenr('$') == 1 && winnr('$') == 1
    return
  endif
  "preparing new window
  let l:tab_nr = tabpagenr('$')
  let l:cur_buf = bufnr('%')
  if tabpagenr() < tab_nr
    close!
    if l:tab_nr == tabpagenr('$')
      tabnext
    endif
    sp
  else
    close!
    tabnew
  endif
  "opening current buffer in new window
  exe "b".l:cur_buf
endfunc

nnoremap mt :call MoveToNextTab()<CR>
nnoremap mT :call MoveToPrevTab()<CR>


" ########
" NERDTree
" ########

nnoremap <F3> :NERDTreeToggle<CR>

let g:NERDTreeIgnore = ['\.pyc$']

" Close vim if NERDTree is the only window open and auto open for every tab
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
autocmd BufWinEnter * NERDTreeMirror
autocmd BufEnter * EnableStripWhitespaceOnSave

" ###############
" Phabricator/Arc
" ###############

nnoremap <leader>ai :ArcInlines<CR>
nnoremap <leader>al :ArcLint<CR>
nnoremap K :grep! "<C-R><C-W>"<CR>:cw<CR>

let fbgrep="~/bin/fbgrep"
if filereadable(fbgrep)
    set grepprg=~/bin/fbgrep
else
    set grepprg=/usr/bin/ag
endif


" #####################
" Goyo/Distraction Free
" #####################

" Map Goyo to key and trigger Limelight when Goyo is active
nnoremap <F9> :Goyo<CR>
autocmd User GoyoEnter Limelight
autocmd User GoyoLeave Limelight!

" ######
" Python
" ######

let python_highlight_all = 1

" ######
" Golang
" ######

let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
" Still not sure if I like all the extra color
" let g:go_highlight_methods = 1
" let g:go_highlight_fields = 1
" let g:go_highlight_types = 1

let g:go_fmt_command = "goimports"
" let g:go_def_mode = "gopls"


au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>c <Plug>(go-coverage)

au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)

au FileType go nmap <Leader>gs <Plug>(go-implements)
au FileType go nmap <leader>gt <Plug>(go-test)
au FileType go nmap <Leader>gr <Plug>(go-rename)

" ##############
" General Editor
" ##############

syntax on                       " enables syntax highlighting
set mouse=a
set hidden                      " multi-file behaviors
set wildmenu                    " better cmd line completion
set wildmode=list:longest       " more shell-like completion
set wildignore=*.swp,*.bak,*.pyc,*.class
set ignorecase                  " case-insensitive matching
set smartcase                   " unless there's upper-case specified
set ruler                       " cursor position
set hlsearch                    " highlight search matches
set incsearch                   " highlight search matches while typing
set nowrap                        " linewraps
set scrolloff=5                 " always show at least 5 lines below/above cur
set title                       " set window title
set visualbell                  " turn off terminal bell
set showbreak=+                 " display + for wrapped lines
set number                      " show line numbers

"Create backup dir if not present
let backupdir_=s:editor_root . '/backup'
if !filereadable(backupdir_)
    silent call mkdir(backupdir_, "p")
endif

set cursorline                  " highlight current row cursor is in
set backup                      " keep a backup file
set backupdir=~/.vim/backup

set showcmd                     " display incomplete commands
set backspace=indent,eol,start

if has("vms")
    set nobackup
endif

" ###############
" File formatting
" ###############

set encoding=utf8               " set utf-8 encoding
set cindent                     " Indent after line ending in { and use cinwords
set ts=4 sw=4 sts=4 expandtab   " Global tab settings
set ai si                       " Auto & smart indent
set textwidth=79
set formatoptions+=r            " Auto insert the current comment prefix
set formatoptions+=q            " Allow formatting of comments with 'gq'
set ffs=unix,dos,mac            " prefer unix linefeed
set pastetoggle=<f5>            " pressing f5 in insert mode will allow pasting

" Maps <Leader>l to highlight current line
" Entering :match will clear highlighting
nnoremap <silent> <Leader>l ml:execute 'match Search /\%'.line('.').'l/'<CR>
                                " without auto indentation being applied.
" History
set history=1000                " 1000 cmd history
set undolevels=1000             " 1000 undo levels

" #####
" Gundo
" #####

nnoremap <F4> :GundoToggle<CR>

" ########
" Markdown
" ########

autocmd BufNewFile,BufRead *.md map <Leader>1 :HeaderDecrease<CR>
autocmd BufNewFile,BufRead *.md map <Leader>2 :HeaderIncrease<CR>
autocmd BufNewFile,BufRead *.md map <Leader>toc :Toch<CR>
let g:vim_markdown_frontmatter=1

" #########
" Colorizer
" #########

let g:colorizer_auto_filetype='css,html,javascript'

" #######
" ALE & LanguageClient
" #######
"
" Required for operations modifying multiple buffers like rename.
set hidden
nnoremap <F5> :call LanguageClient_contextMenu()<CR>
if filereadable('/etc/fbwhoami')
  let g:LanguageClient_rootMarkers = ['.projectid']
  let g:LanguageClient_serverCommands = {
    \ 'cpp': ['/bin/cquery-language-server'],
    \ 'python': ['/usr/local/bin/pyls-language-server'],
    \ 'go': ['/usr/local/bin/fbgo-langserver', '-gocodecompletion', '-logfile=/tmp/nuclide-$USER-logs/golangserver.log'],
  \ }
  let g:ale_python_flake8_executable = '/home/coxley/bin/flakey8'
  let g:ale_python_flake8_args = '--shebang --config /data/users/coxley/fbsource/fbcode/.flake8'
  let g:ale_linters = {
    \    'python': ['flake8'],
  \}
else
    let g:LanguageClient_serverCommands = {
        \ 'python': ['pyls'],
        \ 'go': ['gopls'],
        \ }
endif

let g:ale_fix_on_save = 0
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:airline#extensions#ale#enabled = 1

" ########
" Deoplete
" ########

let g:SuperTabClosePreviewOnPopupClose = 1
let g:SuperTabDefaultCompletionType = "<c-n>"

set completeopt+=noselect
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 1
let g:deoplete#enable_smart_case = 1
"
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#force_py_version = 3
let g:jedi#show_call_signatures = "1"
let g:jedi#popup_on_dot = 0
let g:jedi#show_call_signatures = "2"


autocmd FileType python setlocal completeopt-=preview

" let g:deoplete#sources#jedi#show_docstring = 1
" let g:deoplete#sources#jedi#enable_cache = 1

if !exists('g:deoplete#omni#input_patterns')
  let g:deoplete#omni#input_patterns = {}
endif

let g:jedi#completions_enabled = 1

" inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

" #########
" Clipboard
" #########

set clipboard+=unnamedplus

if !has('nvim')
    :com -range Cz :silent :<line1>,<line2>w !xsel -i -b
    :com -range Cx :silent :<line1>,<line2>w !xsel -i -p
    :com -range Cv :silent :<line1>,<line2>w !xsel -i -s
    :ca cv Cv
    :ca cz Cz
    :ca cx Cx

    :com -range Pz :silent :r !xsel -o -b
    :com -range Px :silent :r !xsel -o -p
    :com -range Pv :silent :r !xsel -o -s

    :ca pz Pz
    :ca px Px
    :ca pv Pv

    function! CopyMatches(reg)
        let hits = []
        %s//\=len(add(hits, submatch(0))) ? submatch(0) : ''/ge
        let reg = empty(a:reg) ? '+' : a:reg
        execute 'let @'.reg.' = join(hits, "\n") . "\n"'
    endfunction
    command! -register CopyMatches call CopyMatches(<q-reg>)
endif


" ##########
" Table Mode
" ##########

nnoremap <silent> <Leader>tm :TableModeToggle

" ####################
" Snippets (Ultisnips)
" ####################

let g:UltiSnipsExpandTrigger='<leader>.'
" let g:UltiSnipsJumpForwardTrigger='<leader>r'
" let g:UltiSnipsJumpBackwardTrigger='<leader>w'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'

nnoremap <leader>ue :UltiSnipsEdit<CR>

let g:UltiSnipsEditSplit='vertical'

let g:UltiSnipsUsePythonVersion = 3
let g:ultisnips_python_style="google"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "vim-snippets", "~/.config/nvim/UltiSnips"]
let g:UltiSnipsSnippetsDir="~/.vim/UltiSnips"

" #########
" Overrides
" #########

let override_file=s:editor_root . 'override.vim'
if filereadable(override_file)
    source override_file
endif

" #######
" Airline
" #######
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" ###########
" SimplylFold
" ###########

set foldlevel=10
let g:SimpylFold_fold_docstring = 0
" autocmd BufWinEnter *.py setlocal foldexpr=SimpylFold(v:lnum) foldmethod=expr
" autocmd BufWinLeave *.py setlocal foldexpr< foldmethod<
nnoremap <space> za
vnoremap <space> zf

" ##########
" indentLine
" ##########

" let g:indentLine_char = '┆'
" " let g:indentLine_char = '¦'
" " let g:indentLine_char = '|'
"
" let g:indentLine_color_term = 239
" let g:indentLine_color_gui = '#A4E57E'
"
" " none X terminal
" let g:indentLine_color_tty_light = 7 " (default: 4)
" let g:indentLine_color_dark = 1 " (default: 2)

" #####################
" Relative Line Numbers
" #####################
" Line number stuff. Set both for hybrid
set number
function! NumberToggle()
  if(&rnu == 1)
      set nornu
    set nu
  elseif(&nu == 1)
    set nonu
    set rnu
  endif
endfunc
nnoremap <leader>i :call NumberToggle()<cr>

" #############
" expand-region
" #############
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" ##############
" vim-grammarous
" ##############
"
" autocmd BufWritePost * silent! :GrammarousCheck
let g:grammarous#default_comments_only_filetypes = {
            \ '*' : 1, 'help' : 0, 'markdown' : 0, 'rst' : 0,
            \ }

let g:grammarous#disabled_rules = {
            \ '*' : ['WHITESPACE_RULE', 'EN_QUOTES', 'COMMA_PARENTHESIS_WHITESPACE'],
            \ 'help' : ['WHITESPACE_RULE', 'EN_QUOTES', 'SENTENCE_WHITESPACE', 'UPPERCASE_SENTENCE_START'],
            \ 'rst' : ['DOUBLE_PUNCTUATION', 'UNPAIRED_BRACKETS'],
            \ 'markdown' : ['DOUBLE_PUNCTUATION', 'UNPAIRED_BRACKETS'],
            \ }

let g:grammarous#disabled_categories = {
            \ '*' : ['PUNCTUATION'],
            \ 'help' : ['PUNCTUATION', 'TYPOGRAPHY'],
            \ 'markdown' : ['PUNCTUATION', 'TYPOGRAPHY'],
            \ 'rst' : ['PUNCTUATION', 'TYPOGRAPHY'],
            \ }


" <C-n> | <C-p> for navigating errors post-check
let g:grammarous#hooks = {}
function! g:grammarous#hooks.on_check(errs) abort
    nmap <buffer><C-n> <Plug>(grammarous-move-to-next-error)
    nmap <buffer><C-p> <Plug>(grammarous-move-to-previous-error)
    nmap <buffer><C-f> <Plug>(grammarous-fixit)
    nmap <buffer><C-i> <Plug>(grammarous-open-info-window)
    nmap <buffer><leader>gF <Plug>(grammarous-fixall)
endfunction

function! g:grammarous#hooks.on_reset(errs) abort
    nunmap <buffer><C-n>
    nunmap <buffer><C-p>
    nunmap <buffer><C-f>
    nunmap <buffer><C-i>
    nunmap <buffer><leader>gF
endfunction



" ######
" Colors
" ######

set background=dark
colorscheme palenight
let g:airline_theme = "hybrid"
"
if filereadable('/etc/fbwhoami')
    if (has("termguicolors"))
        set termguicolors
    endif
endif

" Create wall of highlight passed 89 characters and highlight text
let &colorcolumn=join(range(89,999),",")
highlight colorcolumn ctermbg=235 guibg=#2c2d27
highlight OverLength ctermbg=white ctermfg=red
match OverLength /\%89v.\+/
highlight Search ctermbg='NONE' ctermfg=226
