# zmodload zsh/zprof
[ -f ~/.zsh_pre ] && source ~/.zsh_pre

source ~/.zgen.zsh

if ! zgen-saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh
    zgen load denysdovhan/spaceship-prompt spaceship

    # Custom plugin
    zgen load coxley/zsh-files

    # Shell Syntax Highlighting
    zgen load zsh-users/zsh-syntax-highlighting

    # oh-my-zsh Plugins
    zgen oh-my-zsh plugins/catimg
    zgen oh-my-zsh plugins/common-aliases
    # zgen oh-my-zsh plugins/gcloud
    # zgen oh-my-zsh plugins/git
    # zgen oh-my-zsh plugins/jsontools
    # zgen oh-my-zsh plugins/kubectx
    # zgen oh-my-zsh plugins/pip
    # zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/ssh-agent
    # zgen oh-my-zsh plugins/virtualenv

    # Save zgen profile
    zgen save
fi

setopt PROMPT_SUBST

SPACESHIP_PROMPT_ORDER=(
  # time        # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  # package     # Package version
  # node          # Node.js section
  # ruby          # Ruby section
  # elixir        # Elixir section
  # xcode       # Xcode section
  # swift         # Swift section
  # golang        # Go section
  # php           # PHP section
  # rust          # Rust section
  # haskell       # Haskell Stack section
  # julia       # Julia section
  # docker      # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  # conda         # conda virtualenv section
  # pyenv         # Pyenv section
  # dotnet        # .NET section
  # ember       # Ember.js section
  terraform     # Terraform workspace section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  # vi_mode     # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(kubectl_context)

SPACESHIP_KUBECTL_CONTEXT_COLOR_GROUPS=(
  # red if namespace is "kube-system"
  red    '\(kube-system)$'

  # else, green if "qa" is anywhere in the context or namespace
  green  qa

  # else, red if context name ends with ".k8s.local" _and_ namespace is "system"
  red    '\.k8s\.local \(system)$'

  # else, yellow if "prod" is anywhere in the context or namespace
  yellow prod
)

[ -z $DISPLAY ] || BROWSER=google-chrome-stable

[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
[ -f ~/.zsh_post ] && source ~/.zsh_post
[ -f ~/.zsh_theme ] && source ~/.zsh_theme

# FZF

[ -f ~/.fzf.zsh ] \
    || (
        echo "FZF not installed, installing..."
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
        && ~/.fzf/install \
        && ln -s ~/.fzf/fzf ~/.local/bin/
    )

# [ -f ~/.fzf.zsh ] \
#     && source ~/.fzf.zsh \
#     && _fzf_compgen_path() { ag -g "" "$1" }

# [ -f /usr/bin/wal ] \
#     && (cat ~/.cache/wal/sequences &) \
#     && clear \
#     && source ~/.cache/wal/colors-tty.sh

export FZF_DEFAULT_COMMAND='rg -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
 --color=fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
 --color=info:108,prompt:109,spinner:108,pointer:168,marker:168
'

export HISTSIZE=999999999
export SAVEHIST=999999999
export HISTORY_IGNORE="(history|ls|pwd|exit|ll|*clear) *"

setopt EXTENDED_HISTORY      # Write the history file in the ':start:elapsed;command' format.
setopt INC_APPEND_HISTORY    # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY         # Share history between all sessions.
setopt HIST_IGNORE_DUPS      # Do not record an event that was just recorded again.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_ALL_DUPS  # Delete an old recorded event if a new event is a duplicate.
setopt HIST_IGNORE_SPACE     # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS     # Do not write a duplicate event to the history file.
setopt HIST_VERIFY           # Do not execute immediately upon history expansion.
setopt APPEND_HISTORY        # append to history file (Default)
setopt HIST_NO_STORE         # Don't store history commands
setopt HIST_REDUCE_BLANKS    # Remove superfluous blanks from each command line being added to the history.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.

autoload -U +X bashcompinit && bashcompinit
complete -C /Users/coxley/.go/bin/podrun podrun
complete -C /Users/coxley/.go/bin/logq logq
complete -C /Users/coxley/.go/bin/kflags kflags
# zprof
eval "$(atuin init zsh --disable-up-arrow)"
