[ -f ~/.zsh_pre ] && source ~/.zsh_pre

source ~/.zgen.zsh

if ! zgen-saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # Devservers should have different prompt than my workstations.
    # My workstations are always Arch
    if [[ $(uname -r | grep -o '....$') == "ARCH" ]]; then
        zgen load caiogondim/bullet-train-oh-my-zsh-theme bullet-train
    else
        zgen load denysdovhan/spaceship-prompt spaceship
    fi

    # Custom plugin
    zgen load coxley/zsh-files

    # Shell Syntax Highlighting
    zgen load zsh-users/zsh-syntax-highlighting

    # oh-my-zsh Plugins
    zgen oh-my-zsh plugins/catimg
    zgen oh-my-zsh plugins/common-aliases
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/mercurial
    zgen oh-my-zsh plugins/jsontools
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/python
    zgen oh-my-zsh plugins/sprunge
    zgen oh-my-zsh plugins/ssh-agent
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/systemd
    zgen oh-my-zsh plugins/tmux
    zgen oh-my-zsh plugins/torrent
    zgen oh-my-zsh plugins/virtualenv
    zgen oh-my-zsh plugins/wd

    # Save zgen profile
    zgen save
fi

[ -z $DISPLAY ] || BROWSER=google-chrome-stable

[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
[ -f ~/.zsh_post ] && source ~/.zsh_post
[ -f ~/.zsh_theme ] && source ~/.zsh_theme

# FZF

[ -f ~/.fzf.zsh ] \
    || (
        echo "FZF not installed, installing..."
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf \
        && ~/.fzf/install \
        && ln -s ~/.fzf/fzf ~/.local/bin/
    )

[ -f ~/.fzf.zsh ] \
    && source ~/.fzf.zsh \
    && _fzf_compgen_path() { ag -g "" "$1" }

[ -f /usr/bin/wal ] \
    && (cat ~/.cache/wal/sequences &) \
    && clear \
    && source ~/.cache/wal/colors-tty.sh

export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
 --color=fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
 --color=info:108,prompt:109,spinner:108,pointer:168,marker:168
'
